use local variant

diff --git a/bin/rbenv-install-latest b/bin/rbenv-install-latest
--- a/bin/rbenv-install-latest
+++ b/bin/rbenv-install-latest
@@ -5,15 +5,15 @@ set -e
 DEFAULT_QUERY=2
 
 main() {
-  latest=$(get_version $1)
-  [[ -z $latest ]] && { echo "Ruby version not found." 1>&2; exit 1; }
+  local latest=$(get_version $1)
+  [[ -z $latest ]] && { echo "Ruby version is not found." >&2; exit 1; }
   if confirm "Install $latest?"; then
     rbenv install $latest
   fi
 }
 
 get_version() {
-  query=$1
+  local query=$1
   [[ -z $query ]] && query=$DEFAULT_QUERY
   rbenv install --list \
     | sed 's/^\s\+//' \
